media:
  input: public/static/images/posts
  output: /

content:

# Posts
  - name:  posts
    type:  collection
    label: Posts
    path:  data/blog
    extension: mdx
    filename: "{year}-{month}-{day}-{fields.title}.mdx"
    view:
      fields: [title, date]
      primary: title
    fields:
      - { name: title,       label: Title,            type: string,    required: true, default: "Title"       }
      - { name: draft,       label: Draft,            type: boolean,   required: true, default: true          }
      - { name: date,        label: Publication Date, type: string,    required: true, default: "1970-12-31"  }
      # - { name: tags,        label: Tags,             type: code,      required: true, default: "[]"          }
      - { name: summary,     label: Description,      type: text,      required: true, default: "Description" }
      - { name: body,        label: Body,             type: text,      required: true, default: "Body"        }

# Pages
  - name:  about
    label: About page
    type:  file
    path:  data/authors/default.mdx
    fields:
      # - { name: title, label: Title, type: string }
      # - { name: description, label: Description,  type: text}
      - { name: body, label: Body, type: text}

  - name:  now
    label: Now Page
    type:  file
    path:  data/now/now.mdx
    fields:
      # - { name: title,       label: Title, type: string }
      # - { name: description, label: Description,  type: text}
      - { name: body, label: Body, type: text}

  - name:  roll
    label: Blog Roll
    type:  file
    path:  data/roll/roll.mdx
    fields:
      # - { name: title,  label: Title, type: string }
      # - { name: description, label: Description,  type: text}
      - { name: body, label: Body, type: text}